# Generated by Django 4.2.2 on 2023-07-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendview', '0002_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='category',
        ),
    ]
