# Generated by Django 4.2.2 on 2023-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendview', '0005_alter_answer_category_alter_answer_guardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
