# Generated by Django 4.2.2 on 2023-07-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontendview', '0006_alter_guardian_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='guardian',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontendview.guardian', unique=True),
        ),
    ]
